service: payment
provider:
  name: aws
  runtime: go1.x
  timeout: 60
package:
  exclude:
    - ./**
  include:
    - ./main
functions:
  payment:
    handler: main
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'